run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - revive
    - misspell
    - unconvert
    - unparam
    - gosec
    - gocyclo
    - bodyclose

linters-settings:
  gocyclo:
    min-complexity: 20
  revive:
    rules:
      - name: exported
        severity: warning
        disabled: false
      - name: package-comments
        severity: warning
        disabled: false
  misspell:
    locale: US
  gosec:
    excludes:
      - G115 # Integer overflow conversion (overly strict for our use case)

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - gosec
        - unparam
