version: "2"
run:
  tests: true
linters:
  enable:
    - bodyclose
    - gocyclo
    - gosec
    - revive
    - unconvert
    - unparam
  settings:
    gocyclo:
      min-complexity: 20
    gosec:
      excludes:
        - G115
    misspell:
      locale: US
    revive:
      rules:
        - name: package-comments
          severity: warning
          disabled: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
          - gocyclo
          - gosec
          - revive
          - staticcheck
          - unconvert
          - unparam
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples/
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples/
