version: 2

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - ineffassign
    - revive
    - misspell
    - unconvert
    - unparam
    - gosec
    - gocyclo
    - bodyclose

linters-settings:
  gocyclo:
    min-complexity: 15
  gocognit:
    min-complexity: 20
  revive:
    rules:
      - name: exported
        severity: warning
        disabled: false
      - name: package-comments
        severity: warning
        disabled: false
  misspell:
    locale: US

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - errcheck
        - gosec
        - unparam

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
